# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 04:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_timestamps', related_query_name='challenge_timestamp', to='api.Challenge')),
            ],
            options={
                'verbose_name_plural': 'ChallengeTimestamps',
            },
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numtopteams', models.IntegerField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Scoreboards',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=60, unique=True)),
                ('points', models.IntegerField(default=0)),
                ('correct_flags', models.IntegerField(default=0)),
                ('wrong_flags', models.IntegerField(default=0)),
                ('last_timestamp', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scoreboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team', to='api.Scoreboard')),
                ('solved', models.ManyToManyField(blank=True, related_name='solved', through='api.ChallengeTimestamp', to='api.Challenge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams', related_query_name='team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='challengetimestamp',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_timestamps', related_query_name='challenge_timestamp', to='api.Team'),
        ),
    ]
