# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 05:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170309_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', related_query_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
